In [31]:
import numpy as np

In [32]:
np.random.seed(2112)
X = np.random.randint(10, 101, size=(5, 5))
mu = np.mean(X)
s = np.std(X)

X_normalized = (X - mu) / s
Mean_normalized = np.mean(X_normalized).round()
Std_normalized = np.std(X_normalized).round()

print(F"value of X is:\n{X}\n")
print(F"value of X_normalized is:\n{X_normalized}\n")
print(F"Value of normalized mean is: {Mean_normalized}\n")
print(F"value of normalized standard deviation is: {Std_normalized}")

np.save("X_normalized.npy", X_normalized)

value of X is:
[[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]

value of X_normalized is:
[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]

Value of normalized mean is: 0.0

value of normalized standard deviation is: 1.0


In [33]:
C = (np.arange(1, 101) ** 3).reshape(10, 10)
div_by_4 = C[C % 4 == 0]

print(F"Shape of C: {C.shape}\n")
print(F"Array div_by_4:\n{div_by_4}\n")
print(F"The number of selected elements: {len(div_by_4)}")

np.save("div_by_4.npy", div_by_4)

Shape of C: (10, 10)

Array div_by_4:
[      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]

The number of selected elements: 50


In [34]:
S = (np.arange(1, 37) ** 2).reshape(6,6)
S_mean = np.mean(S)
above_mean = S[S > S_mean]

print(F"Array S:\n{S}\n")
print(F"S_mean: {S_mean}\n")
print(F"Array above_mean:\n{above_mean}\n")
print(F"The number of selected elements: {len(above_mean)}")

np.save("above_mean.npy", above_mean)

Array S:
[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

S_mean: 450.1666666666667

Array above_mean:
[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

The number of selected elements: 15
